### PR TITLE
Gulsen

### PR DESCRIPTION
**Pull request by Gulsen927**
Gulsen class is done

### CODE REVIEW

**Comment by AERKEN** [comment]
very nice!

**Comment by ElenaChubukova** [comment]
excellent job

**Comment by Jewel522** [comment]
Great, first one!

**Review by Jewel522 — APPROVED** [review]
Great

**Review by Jewel522 — APPROVED** [review]
Well Done!

**Review by brandoncab19 — APPROVED** [review]
Well done! Yes, we're group 11

**Comment by eridona22** [comment]
super

**Pull request merged**
