### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by ElenaChubukova**
my codes

### CODE REVIEW

**Comment by eridona22** [comment]
hi

**Review by eridona22 — APPROVED** [review]
hello

**Review by Ali0223 — APPROVED** [review]
nice

**Comment by sinacopur** [comment]
Good

**Review by Gulsen927 — APPROVED** [review]
nice job!

**Comment by sinacopur** [comment]
Good

**Comment by sinacopur** [comment]
Nice

**Comment by brandoncab19** [comment]
Approved

**Comment by eridona22** [comment]
great group.....

**Pull request merged**
