### PR TITLE
Jewel branch

### PR DESCRIPTION
**Pull request by Jewel522**
Hi, have a look

### CODE REVIEW

**Review by sinacopur — APPROVED** [review]

**Review by Gulsen927 — APPROVED** [review]
good job!

**Comment by AERKEN** [comment]
good good study day day up!

**Review by Gulsen927 — APPROVED** [review]
Approved1

**Comment by NurcanKavlak** [comment]
goood

**Review by NurcanKavlak — COMMENTED** [review]
very good

**Comment by NurcanKavlak** [comment]
good job

**Review by brandoncab19 — APPROVED** [review]
Codes look good. Lets merge it!

**Pull request merged**
